version: '2'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-itlab
    environment:
      MYSQL_ROOT_PASSWORD: testing
      MYSQL_DATABASE: it-lab
      MYSQL_USER: itlab
      MYSQL_PASSWORD: itlab
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
      - ~/docker-runtime/mariadb-it-lab:/var/lib/mysql
      - ~/docker-runtime/mariadb-it-lab-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    ports:
      - "33060:3306"
  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma-itlab
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: testing
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
      - "8001:80"
